export const answerChoice: string;
export const choiceWrap: string;
export const endTest: string;
export const inputChoice: string;
export const question: string;
export const resultImg: string;
export const stepStyle: string;
export const textQuestion: string;
export const wrapperTesting: string;
