import { ResponseLoadMeBaseT } from 'app/types/ResponseLoadMeBaseT';

export const defaultUser: ResponseLoadMeBaseT = {
  id: '',
  firstName: '',
  middleName: '',
  lastName: '',
  email: null,
  phone: null,
  role: 'student',
  franchise: {
    id: '',
    isActive: true,
    shortName: '',
    inn: '',
    legalAddress: '',
    actualAddress: '',
    schoolName: '',
    ogrn: '',
    kpp: '',
    checkingAccount: '',
    phone: '',
    email: '',
    city: '',
    bankBill: '',
    bankBik: '',
    bankInn: '',
    bankKpp: '',
    bankName: '',
  },
  city: '',
  birthdate: {
    date: '',
    timezone_type: 0,
    timezone: 'Europe/Moscow',
  },
  sex: false,
  active: false,
  payed: false,
  avatar: null,
  groups: [
    {
      userGroupId: '',
      group: {
        id: '',
        name: '',
        type: 'class',
        status: 'active',
        level: 'easy',
        startedAt: {
          date: '',
          timezone_type: 0,
          timezone: 'Europe/Moscow',
        },
        endedAt: {
          date: '',
          timezone_type: 0,
          timezone: 'Europe/Moscow',
        },
        course: {
          id: '',
          type: 'class',
          status: 'draft',
          title: '',
          level: 'easy',
          worksCount: 3,
          createdAt: {
            date: '2022-08-16 12:07:20.000000',
            timezone_type: 3,
            timezone: 'Europe/Moscow',
          },
          works: [
            {
              id: '1ed1d436-0e84-6932-abe4-a1c8eb1a8fa6',
              index: '1',
              work: {
                id: '1ed01f15-fef4-6142-a0c1-73858328bd50',
                title: 'Caromework',
                text: null,
                type: 'hw',
                createdAt: {
                  date: '1970-01-01 03:00:00.000000',
                  timezone_type: 3,
                  timezone: 'Europe/Moscow',
                },
                gamePresets: [
                  {
                    gamePreset: {
                      id: '1ed16475-0f4b-6ae0-ac4e-5166a7613c98',
                      name: 'someName1',
                      game: {
                        code: 'shulte',
                        name: '\u0422\u0430\u0431\u043b\u0438\u0446\u0430 \u0428\u0443\u043b\u044c\u0442\u0435',
                        type: 'typeOne',
                      },
                      status: 'draft',
                      level: 'easy',
                    },
                  },
                ],
              },
            },
            {
              id: '1ed1d436-0e84-6b58-bf90-a1c8eb1a8fa6',
              index: '2',
              work: {
                id: '1ed03c46-b493-658c-9720-4dadeba52ae5',
                title: 'Caromework',
                text: null,
                type: 'hw',
                createdAt: {
                  date: '1970-01-01 03:00:00.000000',
                  timezone_type: 3,
                  timezone: 'Europe/Moscow',
                },
              },
            },
            {
              id: '1ed1d436-0e84-6c02-9902-a1c8eb1a8fa6',
              index: '3',
              work: {
                id: '1ed06a4d-acc1-6982-bc53-171ef9a54978',
                title:
                  '\u0420\u0430\u0431\u043e\u0447\u0430\u044f \u0440\u0430\u0431\u043e\u0442\u0430',
                text: null,
                type: 'hw',
                createdAt: {
                  date: '1970-01-01 03:00:00.000000',
                  timezone_type: 3,
                  timezone: 'Europe/Moscow',
                },
                tests: [
                  {
                    test: {
                      id: '1ed03c45-b23c-641a-bb1b-d3f0258f28ca',
                      title: 'store1',
                      status: null,
                      createdAt: {
                        date: '1970-01-01 03:00:00.000000',
                        timezone_type: 3,
                        timezone: 'Europe/Moscow',
                      },
                    },
                  },
                ],
              },
            },
          ],
        },
        franchise: {
          id: '',
          isActive: true,
          shortName: '',
          inn: '',
          legalAddress: '',
          actualAddress: '',
          schoolName: '',
          ogrn: '',
          kpp: '',
          checkingAccount: '',
          phone: '',
          email: '',
          city: '',
          bankBill: '',
          bankBik: '',
          bankInn: '',
          bankKpp: '',
          bankName: '',
        },
        users: [
          {
            id: '',
            stats: [],
            user: {
              id: '',
              firstName: '',
              middleName: '',
              lastName: '',
              phone: '',
              email: '',
              roleCode: '',
              franchise: {
                id: '',
                shortName: '',
              },
              city: '',
              birthdate: {
                date: '',
                timezone_type: 3,
                timezone: 'Europe/Moscow',
              },
              sex: true,
              createdAt: {
                date: '',
                timezone_type: 3,
                timezone: 'Europe/Moscow',
              },
              groups: [
                {
                  userGroupId: '1ed1d468-4671-60c0-a525-0fb48a16d6d3',
                  groupId: '1ed1d441-c3d6-6e2e-81c4-0192ec76f502',
                  groupCode: 'GROUP KLASS',
                  groupType: 'class',
                },
              ],
              parents: [
                {
                  parentingId: '',
                  isMain: true,
                  parent: {
                    id: '',
                    firstName: '',
                    middleName: '',
                    lastName: '',
                    avatar: null,
                    role: 'parent',
                    sex: true,
                    birthdate: {
                      date: '',
                      timezone_type: 3,
                      timezone: 'Europe/Moscow',
                    },
                    city: '',
                    phone: '',
                    email: '',
                  },
                },
              ],
              active: true,
              payed: false,
              avatar: null,
              tariff: null,
              payedUntill: null,
              isSecondChild: null,
              status: 'notPayed',
              canSwitchTo: [],
            },
          },
        ],
        schedule: [
          {
            name: '',
            date: '17.08.22',
            from: '09:00',
            to: '09:45',
          },
        ],
        teacherId: '',
      },
    },
  ],
  canSwitchTo: [],
  parent: {
    id: '',
    firstName: '',
    middleName: '',
    lastName: '',
    phone: '',
    email: '',
  },
  personalRecord: {
    a: null,
    b: null,
    c: null,
  },
};
