export const Routes = {
  Index: '/',
  Administrator: '/administrator',
  AddHomework: '/add-homework',
  AddNews: '/add-news',
  AddText: '/add-text',
  Dashboard: '/dashboard',
  BlockShulte: '/block-shulte',
  CuratorHome: '/curator-home',
  Classes: '/classes',
  ForgotPassword: '/account/forgot-password',
  FranchiseeAdministratorMain: '/franchisee-administrator-main',
  Payment: '/payment',
  PersonaData: '/persona-data',
  ResetPassword: '/account/reset-password',
  Results: '/result',
  Signin: '/account/signin',
  Signout: '/account/signout',
  Signup: '/account/signup',
  Scenario: '/scenario',
  StatisticsTeachers: '/statistics-teachers',
  Tariff: '/tariff',
  SettingGames: '/setting-games',
  TeacherItemResult: '/teacher-item-result',
  TeacherMain: '/teacher-main',
  Testing: '/testing',
};
