export const Routes = {
  Index: '/',
  Dashboard: '/dashboard',
  Signin: '/account/signin',
  Signout: '/account/signout',
  Signup: '/account/signup',
  ForgotPassword: '/account/forgot-password',
  ResetPassword: '/account/reset-password',
  Results: '/results',
  Payment: '/payment',
  Administrator: '/administrator',
  Result: '/result',
  TeacherMain: '/teacher-main',
  TeacherItemResult: '/teacher-item-result',
  Testing: '/testing',
  PagePersonaData: '/persona-data',
  BlockShulte: '/block-shulte',
};
