export const Routes = {
  Index: '/',
  Dashboard: '/dashboard',
  Signin: '/account/signin',
  Signout: '/account/signout',
  Signup: '/account/signup',
  ForgotPassword: '/account/forgot-password',
  ResetPassword: '/account/reset-password',
  Results: '/result',
  Scenario: '/scenario',
  Payment: '/payment',
  Administrator: '/administrator',
  StatisticsTeachers: '/statistics-teachers',
  CuratorHome: '/curator-home',
  AddHomework: '/add-homework',
  Tariff: '/tariff',
  AddNews: '/add-news',
  AddText: '/add-text',
  Classes: '/classes',
  FranchiseeAdministratorMain: '/franchisee-administrator-main',
  SettingGames: '/setting-games',
};
