export const addBlock: string;
export const addField: string;
export const btnBlock: string;
export const content: string;
export const editorBlock: string;
export const editorWrapper: string;
export const innerContent: string;
export const inputWrap: string;
export const wrapContent: string;
