export const addBtn: string;
export const code: string;
export const cost: string;
export const from: string;
export const innerContent: string;
export const name: string;
export const start: string;
export const tariff: string;
export const text: string;
