export const flag: string;
export const image: string;
export const list: string;
export const mt20: string;
export const row: string;
export const rowWrapper: string;
export const settings: string;
export const title: string;
export const wrapper: string;
