export const AppRoutes = {
  Index: '/',
  Statistic: '/statistic',
  Games: '/games',
  Blog: '/blog',
  Classes: '/classes',
  Courses: '/classes',
  Signin: '/account/signin',
  Signout: '/account/signout',
  Signup: '/account/signup',
  ForgotPassword: '/account/forgot-password',
  Payment: '/pay',
  ResetPassword: '/account/reset-password',
  Schedule: '/schedule',
  Testing: '/testing',
  UserInfo: '/user-info',
  Olympiads: '/olympiads',
  Users: '/users',
  Report: '/report',
  Homework: '/homework',
  Franchising: '/franchising',
  Rate: '/rate',
  Add: '/add',
};
