export enum Paths {
  Auth = 'auth',
  Login = 'login',
  SMS = 'sms',
  Me = 'me',
  LoadMe = 'loadme',
  Franchises = 'franchises',
  Courses = 'courses',
  Works = 'works',
  Users = 'users',
  Parentings = 'parentings',
  Presets = 'gamepresets',
  Groups = 'groups',
  Register = 'register',
  Games = 'games',
  Tariffs = 'tariffs',
  Avatar = 'avatar_upload',
  EditSelf = 'editself',
  UserGroups = 'usergroups',
  Tests = 'tests',
  ArticleTestResults = 'articletestresults',
  Articles = 'articles',
}
