export enum Paths {
  Auth = 'api/v1/auth',
  Login = 'api/v1/login',
  SMS = 'api/v1/sms',
  Me = 'api/v1/me',
  LoadMe = 'api/v1/loadme',
  Franchises = '/api/v1/franchises',
  Courses = '/api/v1/courses',
  Works = '/api/v1/works',
  Users = '/api/v1/users',
  Parentings = '/api/v1/parentings',
  Presets = '/api/v1/gamepresets',
  Groups = '/api/v1/groups',
  Register = '/api/v1/register',
  Games = '/api/v1/games',
  Tariffs = '/api/v1/tariffs',
  Avatar = '/api/v1/avatar_upload',
  EditSelf = '/api/v1/editself',
}
