export const container: string;
export const description: string;
export const gameTitle: string;
export const minutesLeft: string;
export const needToDoContainer: string;
export const needToDoTitle: string;
export const tip: string;
export const tips: string;
export const tipsTitle: string;
